name: Build and Package
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
jobs:
  build-publish:
    timeout-minutes: 60
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        run: pip install poetry

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish
